# Generated by Django 5.2 on 2025-04-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('USER', 'Utilisateur')], default='USER', max_length=13),
        ),
    ]
