# Generated by Django 5.2 on 2025-04-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
