# Generated by Django 5.2 on 2025-04-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0003_livre_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='Prix (€)'),
        ),
    ]
