# Generated by Django 5.2 on 2025-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0009_reservation_prochainedateretour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dateRetour',
            field=models.DateField(blank=True, null=True),
        ),
    ]
