# Generated by Django 5.2 on 2025-05-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0013_reservation_esteffectuee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='estAnnulee',
            field=models.BooleanField(default=False),
        ),
    ]
