# Generated by Django 5.2 on 2025-05-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0017_remove_emprunt_dateretoureffective'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='dateRetourEffective',
            field=models.DateField(blank=True, null=True),
        ),
    ]
