# Generated by Django 5.2 on 2025-05-07 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0018_emprunt_dateretoureffective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('amende', 'Amende'), ('abonnement', 'Abonnement'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('description', models.TextField()),
                ('est_paye', models.BooleanField(default=True)),
                ('amende', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus', to='BibloApp.amende')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus', to='BibloApp.payment')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='BibloApp.utilisateur')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
                'ordering': ['-date_creation'],
            },
        ),
    ]
