# Generated by Django 5.2 on 2025-05-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0019_recu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recu',
        ),
    ]
