# Generated by Django 5.2 on 2025-04-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0005_alter_livre_prix_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='estDisponible',
        ),
    ]
