# Generated by Django 5.2 on 2025-04-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0006_payment_add_price'),
        ('BibloApp', '0006_remove_livre_estdisponible'),
    ]

    operations = [
    ]
