# Generated by Django 5.2 on 2025-05-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0007_merge_20250427_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dateRetour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='BibloApp.emprunt'),
        ),
    ]
