# Generated by Django 5.2 on 2025-05-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0008_reservation_dateretour'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ProchaineDateRetour',
            field=models.DateField(blank=True, null=True),
        ),
    ]
