# Generated by Django 5.2 on 2025-05-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0012_alter_reservation_dateretour'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='estEffectuee',
            field=models.BooleanField(default=False),
        ),
    ]
