# Generated by Django 5.2 on 2025-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0015_rename_dateretour_emprunt_dateretourprevue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('Emprunt', 'Emprunt'), ('Reservation', 'Réservation')], default='Emprunt', max_length=20),
        ),
    ]
