# Generated by Django 5.2 on 2025-05-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BibloApp', '0016_payment_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='dateRetourEffective',
        ),
    ]
